export { usage } from './Avatar.demo.usage';
export { placeholders } from './Avatar.demo.placeholders';
export { configurator } from './Avatar.demo.configurator';
export { link } from './Avatar.demo.link';
export { group } from './Avatar.demo.group';
export { groupTooltip } from './Avatar.demo.groupTooltip';
export { gradient } from './Avatar.demo.gradient';
export { initials } from './Avatar.demo.initials';
export { allowedColors } from './Avatar.demo.allowedColors';
