import {
  IconBox,
  IconBoxMultiple,
  IconBulb,
  IconClick,
  IconComponents,
  IconForms,
  IconLayout2,
  IconLetterCase,
  IconMenu2,
  IconNotebook,
  IconRefresh,
  IconSelector,
  IconSpeakerphone,
} from '@tabler/icons-react';

export const CATEGORY_ICONS: Record<string, typeof IconBox> = {
  'State management': IconBox,
  'UI and Dom': IconForms,
  Utilities: IconBulb,
  Lifecycle: IconRefresh,
  'Data display': IconNotebook,
  overlays: IconBoxMultiple,
  navigation: IconMenu2,
  inputs: IconForms,
  misc: IconComponents,
  feedback: IconSpeakerphone,
  typography: IconLetterCase,
  layout: IconLayout2,
  buttons: IconClick,
  combobox: IconSelector,
};
