name: Report an issue with @mantine/ scoped package
description: Tell us if something is not working as expected
labels: 'review required'
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reaching out!
        Before submitting an issue please make sure that you use latest version of all @mantine/ packages.
  - type: dropdown
    id: package
    attributes:
      label: What package has an issue
      options:
        - '@mantine/core'
        - '@mantine/dates'
        - '@mantine/hooks'
        - '@mantine/form'
        - '@mantine/notifications'
        - '@mantine/tiptap'
        - '@mantine/prism'
        - '@mantine/modals'
        - '@mantine/dropzone'
        - '@mantine/spotlight'
        - '@mantine/nprogress'
        - '@mantine/carousel'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version of @mantine/hooks page do you have in package.json?
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: If possible, please include a link to a codesandbox with the reproduced problem
      description: Codesandbox template – https://codesandbox.io/s/mantine-template-9ze89
  - type: dropdown
    id: fix
    attributes:
      label: Do you know how to fix the issue
      options:
        - 'Yes'
        - 'No'
  - type: dropdown
    id: participate
    attributes:
      label: Are you willing to participate in fixing this issue and create a pull request with the fix
      options:
        - 'Yes'
        - 'No'
  - type: textarea
    id: possibleFix
    attributes:
      label: Possible fix
