name: Report an issue with @mantine/ scoped package
description: Tell us if something is not working as expected
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reaching out!
        Before submitting an issue please make sure that you use latest version of all @mantine/* packages.
  - type: dropdown
    id: package
    attributes:
      label: What package has an issue?
      options:
        - '@mantine/core'
        - '@mantine/dates'
        - '@mantine/hooks'
        - '@mantine/form'
        - '@mantine/notifications'
        - '@mantine/tiptap'
        - '@mantine/code-highlight'
        - '@mantine/modals'
        - '@mantine/dropzone'
        - '@mantine/spotlight'
        - '@mantine/nprogress'
        - '@mantine/carousel'
        - '@mantine/colors-generator'
        - '@mantine/store'
        - '@mantine/vanilla-extract'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: If possible, please include a link to a codesandbox with a minimal reproduction
      description: Codesandbox template – https://codesandbox.io/s/mantine-template-9ze89
  - type: dropdown
    id: fix
    attributes:
      label: Do you know how to fix the issue
      options:
        - 'Yes'
        - 'No'
  - type: dropdown
    id: participate
    attributes:
      label: Do you want to send a pull request with a fix?
      options:
        - 'Yes'
        - 'No'
  - type: textarea
    id: possibleFix
    attributes:
      label: Possible fix
