blank_issues_enabled: true
contact_links:
  - name: Ask a question, give feedback, share your project
    url: https://github.com/mantinedev/mantine/discussions
    about: Connect with other community members with GitHub discussions
  - name: Get help on Discord
    url: https://discord.gg/eUZpPbpxb4
    about: Get help from maintainers on Discord
