import { type MatrixChartCell, MatrixChart } from '@mantine/charts';
import { MantineDemo } from '@mantinex/demo';

const data: MatrixChartCell[] = [
  { x: '1', y: 'James', value: 7 },
  { x: '2', y: 'James', value: 10 },
  { x: '3', y: 'James', value: 2 },
  { x: '4', y: 'James', value: 10 },
  { x: '5', y: 'James', value: 8 },
  { x: '6', y: 'James', value: null },
  { x: '7', y: 'James', value: null },
  { x: '8', y: 'James', value: 6 },
  { x: '9', y: 'James', value: 2 },
  { x: '10', y: 'James', value: 8 },
  { x: '11', y: 'James', value: 1 },
  { x: '12', y: 'James', value: 3 },
  { x: '13', y: 'James', value: 7 },
  { x: '14', y: 'James', value: null },
  { x: '15', y: 'James', value: 9 },
  { x: '16', y: 'James', value: 10 },
  { x: '17', y: 'James', value: null },
  { x: '18', y: 'James', value: 1 },
  { x: '19', y: 'James', value: 8 },
  { x: '20', y: 'James', value: null },
  { x: '21', y: 'James', value: null },
  { x: '22', y: 'James', value: 5 },
  { x: '23', y: 'James', value: 8 },
  { x: '24', y: 'James', value: 2 },
  { x: '25', y: 'James', value: 5 },
  { x: '26', y: 'James', value: 6 },
  { x: '27', y: 'James', value: null },
  { x: '28', y: 'James', value: null },
  { x: '29', y: 'James', value: 7 },
  { x: '30', y: 'James', value: 7 },
  { x: '31', y: 'James', value: 6 },
  { x: '1', y: 'Mary', value: 3 },
  { x: '2', y: 'Mary', value: 1 },
  { x: '3', y: 'Mary', value: 8 },
  { x: '4', y: 'Mary', value: 2 },
  { x: '5', y: 'Mary', value: 2 },
  { x: '6', y: 'Mary', value: null },
  { x: '7', y: 'Mary', value: null },
  { x: '8', y: 'Mary', value: 10 },
  { x: '9', y: 'Mary', value: 1 },
  { x: '10', y: 'Mary', value: 8 },
  { x: '11', y: 'Mary', value: 8 },
  { x: '12', y: 'Mary', value: 3 },
  { x: '13', y: 'Mary', value: null },
  { x: '14', y: 'Mary', value: null },
  { x: '15', y: 'Mary', value: 9 },
  { x: '16', y: 'Mary', value: 7 },
  { x: '17', y: 'Mary', value: 5 },
  { x: '18', y: 'Mary', value: 5 },
  { x: '19', y: 'Mary', value: 3 },
  { x: '20', y: 'Mary', value: null },
  { x: '21', y: 'Mary', value: 3 },
  { x: '22', y: 'Mary', value: 3 },
  { x: '23', y: 'Mary', value: 1 },
  { x: '24', y: 'Mary', value: 4 },
  { x: '25', y: 'Mary', value: 5 },
  { x: '26', y: 'Mary', value: 6 },
  { x: '27', y: 'Mary', value: null },
  { x: '28', y: 'Mary', value: null },
  { x: '29', y: 'Mary', value: 9 },
  { x: '30', y: 'Mary', value: 8 },
  { x: '31', y: 'Mary', value: 2 },
  { x: '1', y: 'Robert', value: 6 },
  { x: '2', y: 'Robert', value: 3 },
  { x: '3', y: 'Robert', value: 3 },
  { x: '4', y: 'Robert', value: 5 },
  { x: '5', y: 'Robert', value: 8 },
  { x: '6', y: 'Robert', value: 7 },
  { x: '7', y: 'Robert', value: null },
  { x: '8', y: 'Robert', value: 9 },
  { x: '9', y: 'Robert', value: 5 },
  { x: '10', y: 'Robert', value: 2 },
  { x: '11', y: 'Robert', value: 3 },
  { x: '12', y: 'Robert', value: 5 },
  { x: '13', y: 'Robert', value: null },
  { x: '14', y: 'Robert', value: 1 },
  { x: '15', y: 'Robert', value: 2 },
  { x: '16', y: 'Robert', value: 8 },
  { x: '17', y: 'Robert', value: 9 },
  { x: '18', y: 'Robert', value: 1 },
  { x: '19', y: 'Robert', value: 1 },
  { x: '20', y: 'Robert', value: null },
  { x: '21', y: 'Robert', value: null },
  { x: '22', y: 'Robert', value: 9 },
  { x: '23', y: 'Robert', value: 2 },
  { x: '24', y: 'Robert', value: 4 },
  { x: '25', y: 'Robert', value: 8 },
  { x: '26', y: 'Robert', value: 10 },
  { x: '27', y: 'Robert', value: null },
  { x: '28', y: 'Robert', value: null },
  { x: '29', y: 'Robert', value: 9 },
  { x: '30', y: 'Robert', value: 3 },
  { x: '31', y: 'Robert', value: 2 },
  { x: '1', y: 'Linda', value: 5 },
  { x: '2', y: 'Linda', value: 6 },
  { x: '3', y: 'Linda', value: 9 },
  { x: '4', y: 'Linda', value: 1 },
  { x: '5', y: 'Linda', value: 2 },
  { x: '6', y: 'Linda', value: null },
  { x: '7', y: 'Linda', value: null },
  { x: '8', y: 'Linda', value: 3 },
  { x: '9', y: 'Linda', value: 3 },
  { x: '10', y: 'Linda', value: 9 },
  { x: '11', y: 'Linda', value: 8 },
  { x: '12', y: 'Linda', value: 6 },
  { x: '13', y: 'Linda', value: 6 },
  { x: '14', y: 'Linda', value: null },
  { x: '15', y: 'Linda', value: 2 },
  { x: '16', y: 'Linda', value: 4 },
  { x: '17', y: 'Linda', value: 6 },
  { x: '18', y: 'Linda', value: 5 },
  { x: '19', y: 'Linda', value: null },
  { x: '20', y: 'Linda', value: 2 },
  { x: '21', y: 'Linda', value: null },
  { x: '22', y: 'Linda', value: 4 },
  { x: '23', y: 'Linda', value: 6 },
  { x: '24', y: 'Linda', value: null },
  { x: '25', y: 'Linda', value: 5 },
  { x: '26', y: 'Linda', value: 10 },
  { x: '27', y: 'Linda', value: null },
  { x: '28', y: 'Linda', value: null },
  { x: '29', y: 'Linda', value: 1 },
  { x: '30', y: 'Linda', value: 10 },
  { x: '31', y: 'Linda', value: 1 },
  { x: '1', y: 'Michael', value: 6 },
  { x: '2', y: 'Michael', value: 9 },
  { x: '3', y: 'Michael', value: 3 },
  { x: '4', y: 'Michael', value: 4 },
  { x: '5', y: 'Michael', value: 3 },
  { x: '6', y: 'Michael', value: null },
  { x: '7', y: 'Michael', value: null },
  { x: '8', y: 'Michael', value: 8 },
  { x: '9', y: 'Michael', value: 7 },
  { x: '10', y: 'Michael', value: 2 },
  { x: '11', y: 'Michael', value: 7 },
  { x: '12', y: 'Michael', value: 7 },
  { x: '13', y: 'Michael', value: 9 },
  { x: '14', y: 'Michael', value: 5 },
  { x: '15', y: 'Michael', value: 8 },
  { x: '16', y: 'Michael', value: 4 },
  { x: '17', y: 'Michael', value: 7 },
  { x: '18', y: 'Michael', value: null },
  { x: '19', y: 'Michael', value: 5 },
  { x: '20', y: 'Michael', value: null },
  { x: '21', y: 'Michael', value: null },
  { x: '22', y: 'Michael', value: 7 },
  { x: '23', y: 'Michael', value: 4 },
  { x: '24', y: 'Michael', value: 7 },
  { x: '25', y: 'Michael', value: 5 },
  { x: '26', y: 'Michael', value: 2 },
  { x: '27', y: 'Michael', value: null },
  { x: '28', y: 'Michael', value: 2 },
  { x: '29', y: 'Michael', value: null },
  { x: '30', y: 'Michael', value: 8 },
  { x: '31', y: 'Michael', value: 9 },
  { x: '1', y: 'Sarah', value: 2 },
  { x: '2', y: 'Sarah', value: 5 },
  { x: '3', y: 'Sarah', value: 2 },
  { x: '4', y: 'Sarah', value: 2 },
  { x: '5', y: 'Sarah', value: 3 },
  { x: '6', y: 'Sarah', value: null },
  { x: '7', y: 'Sarah', value: 5 },
  { x: '8', y: 'Sarah', value: 9 },
  { x: '9', y: 'Sarah', value: 3 },
  { x: '10', y: 'Sarah', value: 10 },
  { x: '11', y: 'Sarah', value: 9 },
  { x: '12', y: 'Sarah', value: 5 },
  { x: '13', y: 'Sarah', value: 3 },
  { x: '14', y: 'Sarah', value: null },
  { x: '15', y: 'Sarah', value: 5 },
  { x: '16', y: 'Sarah', value: 9 },
  { x: '17', y: 'Sarah', value: 6 },
  { x: '18', y: 'Sarah', value: 9 },
  { x: '19', y: 'Sarah', value: 4 },
  { x: '20', y: 'Sarah', value: null },
  { x: '21', y: 'Sarah', value: 5 },
  { x: '22', y: 'Sarah', value: 9 },
  { x: '23', y: 'Sarah', value: 8 },
  { x: '24', y: 'Sarah', value: 2 },
  { x: '25', y: 'Sarah', value: 5 },
  { x: '26', y: 'Sarah', value: 5 },
  { x: '27', y: 'Sarah', value: 2 },
  { x: '28', y: 'Sarah', value: null },
  { x: '29', y: 'Sarah', value: 8 },
  { x: '30', y: 'Sarah', value: 2 },
  { x: '31', y: 'Sarah', value: 8 },
  { x: '1', y: 'David', value: 3 },
  { x: '2', y: 'David', value: 8 },
  { x: '3', y: 'David', value: 2 },
  { x: '4', y: 'David', value: 10 },
  { x: '5', y: 'David', value: 1 },
  { x: '6', y: 'David', value: 6 },
  { x: '7', y: 'David', value: null },
  { x: '8', y: 'David', value: 1 },
  { x: '9', y: 'David', value: 5 },
  { x: '10', y: 'David', value: 3 },
  { x: '11', y: 'David', value: 1 },
  { x: '12', y: 'David', value: 2 },
  { x: '13', y: 'David', value: null },
  { x: '14', y: 'David', value: null },
  { x: '15', y: 'David', value: 1 },
  { x: '16', y: 'David', value: 2 },
  { x: '17', y: 'David', value: 1 },
  { x: '18', y: 'David', value: 2 },
  { x: '19', y: 'David', value: null },
  { x: '20', y: 'David', value: null },
  { x: '21', y: 'David', value: null },
  { x: '22', y: 'David', value: 7 },
  { x: '23', y: 'David', value: 7 },
  { x: '24', y: 'David', value: 2 },
  { x: '25', y: 'David', value: 5 },
  { x: '26', y: 'David', value: 5 },
  { x: '27', y: 'David', value: null },
  { x: '28', y: 'David', value: null },
  { x: '29', y: 'David', value: 5 },
  { x: '30', y: 'David', value: 6 },
  { x: '31', y: 'David', value: 2 },
  { x: '1', y: 'Emma', value: 8 },
  { x: '2', y: 'Emma', value: 9 },
  { x: '3', y: 'Emma', value: 10 },
  { x: '4', y: 'Emma', value: 4 },
  { x: '5', y: 'Emma', value: 5 },
  { x: '6', y: 'Emma', value: null },
  { x: '7', y: 'Emma', value: null },
  { x: '8', y: 'Emma', value: 1 },
  { x: '9', y: 'Emma', value: 6 },
  { x: '10', y: 'Emma', value: 6 },
  { x: '11', y: 'Emma', value: 2 },
  { x: '12', y: 'Emma', value: 6 },
  { x: '13', y: 'Emma', value: null },
  { x: '14', y: 'Emma', value: null },
  { x: '15', y: 'Emma', value: 2 },
  { x: '16', y: 'Emma', value: 4 },
  { x: '17', y: 'Emma', value: 2 },
  { x: '18', y: 'Emma', value: 9 },
  { x: '19', y: 'Emma', value: 7 },
  { x: '20', y: 'Emma', value: null },
  { x: '21', y: 'Emma', value: 2 },
  { x: '22', y: 'Emma', value: 9 },
  { x: '23', y: 'Emma', value: 5 },
  { x: '24', y: 'Emma', value: 6 },
  { x: '25', y: 'Emma', value: 9 },
  { x: '26', y: 'Emma', value: 9 },
  { x: '27', y: 'Emma', value: null },
  { x: '28', y: 'Emma', value: null },
  { x: '29', y: 'Emma', value: 6 },
  { x: '30', y: 'Emma', value: 1 },
  { x: '31', y: 'Emma', value: 5 },
];

const dataCode = `import { MatrixChartCell } from '@mantine/charts';

export const data: MatrixChartCell[] = [
  { x: '1', y: 'James', value: 7 },
  { x: '2', y: 'James', value: 10 },
  { x: '3', y: 'James', value: 2 },
  { x: '4', y: 'James', value: 10 },
  { x: '5', y: 'James', value: 8 },
  { x: '6', y: 'James', value: null },
  { x: '7', y: 'James', value: null },
  { x: '8', y: 'James', value: 6 },
  { x: '9', y: 'James', value: 2 },
  { x: '10', y: 'James', value: 8 },
  { x: '11', y: 'James', value: 1 },
  { x: '12', y: 'James', value: 3 },
  { x: '13', y: 'James', value: 7 },
  { x: '14', y: 'James', value: null },
  { x: '15', y: 'James', value: 9 },
  { x: '16', y: 'James', value: 10 },
  { x: '17', y: 'James', value: null },
  { x: '18', y: 'James', value: 1 },
  { x: '19', y: 'James', value: 8 },
  { x: '20', y: 'James', value: null },
  { x: '21', y: 'James', value: null },
  { x: '22', y: 'James', value: 5 },
  { x: '23', y: 'James', value: 8 },
  { x: '24', y: 'James', value: 2 },
  { x: '25', y: 'James', value: 5 },
  { x: '26', y: 'James', value: 6 },
  { x: '27', y: 'James', value: null },
  { x: '28', y: 'James', value: null },
  { x: '29', y: 'James', value: 7 },
  { x: '30', y: 'James', value: 7 },
  { x: '31', y: 'James', value: 6 },
  { x: '1', y: 'Mary', value: 3 },
  { x: '2', y: 'Mary', value: 1 },
  // ... remaining data
];`;

const code = `
import { MatrixChart } from '@mantine/charts';
import { data } from './data';

function Demo() {
  return (
    <MatrixChart
      data={data}
      yLabels={['James', 'Mary', 'Robert', 'Linda', 'Michael', 'Sarah', 'David', 'Emma']}
      withYLabels
      withTooltip
      getTooltipLabel={({ x, y, value }) =>
        \`\${y}, Mar \${x}: \${value === null ? 'No contributions' : \`\${value} contribution\${value > 1 ? 's' : ''}\`}\`
      }
    />
  );
}
`;

function Demo() {
  return (
    <MatrixChart
      data={data}
      yLabels={['James', 'Mary', 'Robert', 'Linda', 'Michael', 'Sarah', 'David', 'Emma']}
      withYLabels
      withTooltip
      getTooltipLabel={({ x, y, value }) =>
        `${y}, Mar ${x}: ${value === null ? 'No contributions' : `${value} contribution${value > 1 ? 's' : ''}`}`
      }
    />
  );
}

export const usage: MantineDemo = {
  type: 'code',
  component: Demo,
  centered: true,
  overflow: 'hidden',
  code: [
    { fileName: 'Demo.tsx', code, language: 'tsx' },
    { fileName: 'data.ts', code: dataCode, language: 'tsx' },
  ],
};
