export const MIME_TYPES = {
 // Images
 png: "image/png",
 gif: "image/gif",
 jpeg: "image/jpeg",
 svg: "image/svg+xml",
 webp: "image/webp",
 jpg: "image/jpeg",
 ico: "image/x-icon",
 tiff: "image/tiff",

 // Videos
 mp4: "video/mp4",
 ogv: "video/ogg",
 webm: "video/webm",
 qt: "video/quicktime",
 mov: "video/quicktime",
 avi: "video/x-msvideo",
 wmv: "video/x-ms-wmv",
 mpg: "video/mpeg",
 mpeg: "video/mpeg",
 mpe: "video/mpeg",
 m4v: "video/mp4",
 flv: "video/x-flv",

 // Audio
 mp3: "audio/mpeg",
 ogg: "audio/ogg",
 wav: "audio/wav",
 wma: "audio/x-ms-wma",
 m4a: "audio/mp4",
 aac: "audio/aac",
 flac: "audio/flac",
 mid: "audio/midi",
 midi: "audio/midi",
 ra: "audio/x-pn-realaudio",
 ram: "audio/x-pn-realaudio",
 rm: "audio/x-pn-realaudio",
 aif: "audio/x-aiff",
 aiff: "audio/x-aiff",
 aifc: "audio/x-aiff",
 caf: "audio/x-caf",

 // Executables
 exe: "application/vnd.microsoft.portable-executable",
 dmg: "application/x-apple-diskimage",
 iso: "application/x-iso9660-image",
 msi: "application/x-msdownload",
 nsis: "application/x-nsis-project",
 sh: "application/x-sh",
 lha: "application/x-lzh-compressed",
 lzh: "application/x-lzh-compressed",
 app: "application/x-ms-dos-executable",
 bat: "application/x-msdos-program",
 cmd: "application/x-msdos-program",
 com: "application/x-msdos-program",
 dll: "application/x-msdos-program",
 vbs: "application/x-msdos-program",
 msp: "application/x-ms-project",
 mst: "application/x-msdos-program",
 pif: "application/x-msdos-program",
 scr: "application/x-ms-shortcut",
 sis: "application/vnd.symbian.install",
 wxl: "application/x-wxl",
 wxi: "application/x-wxl",

 // Archives
 zip: "application/zip",
 rar: "application/x-rar-compressed",
 gz: "application/gzip",
 bz2: "application/x-bzip2",
 cab: "application/vnd.ms-cab-compressed",
 arj: "application/x-arj",
 tar: "application/x-tar",
 "7z": "application/x-7z-compressed",
 tgz: "application/x-compressed-tar",
 tbz: "application/x-bzip-compressed-tar",
 tbz2: "application/x-bzip-compressed-tar",
 taz: "application/x-bzip-compressed-tar",
 deb: "application/x-debian-package",
 rpm: "application/x-redhat-package-manager",
 z: "application/x-compress",
 xz: "application/x-xz",
 txz: "application/x-xz",
 gzip: "application/x-gzip",
 bz: "application/x-bzip",
 bzip: "application/x-bzip",
 bzip2: "application/x-bzip2",
 rz: "application/x-rzip",
 rzip: "application/x-rzip",
 ace: "application/x-ace-compressed",

 // 3D Models
 stl: "model/stl",
 obj: "model/obj",
 dae: "model/vnd.collada+xml",
 wrl: "model/vrml",
 x3d: "model/x3d+xml",
 x3db: "model/x3d+binary",
 x3dv: "model/x3d+vrml",
 x3dvz: "model/x3d+vrml",
 x3dz: "model/x3d+xml",
 x3dbz: "model/x3d+binary",

 // Programming Languages
 js: "application/javascript",
 json: "application/json",
 ts: "application/typescript",
 coffee: "application/coffeescript",
 css: "text/css",
 c: "text/x-c",
 cpp: "text/x-c++src",
 h: "text/x-c++hdr",
 hpp: "text/x-c++hdr",
 hxx: "text/x-c++hdr",
 cc: "text/x-c++src",
 cxx: "text/x-c++src",
 go: "text/x-go",
 java: "text/x-java",
 csv: "text/csv",
 xml: "text/xml",
 xsl: "text/xml",
 xslt: "text/xml",
 rss: "application/rss+xml",
 atom: "application/atom+xml",
 rdf: "application/rdf+xml",
 n3: "text/n3",
 ntriples: "text/n3",
 turtle: "text/turtle",
 rdfa: "text/rdfa",
 rdfb: "text/rdf+xml",
 rj: "application/x-ruby",
 rb: "application/x-ruby",
 erb: "application/x-ruby",
 erl: "text/x-erlang",
 erlang: "text/x-erlang",
 pl: "text/x-perl",
 py: "text/x-python",
 rbx: "text/x-ruby",
 rhtml: "text/html",
 rjs: "text/javascript",
 rt: "text/vnd.rn-realtext",
 rtf: "text/rtf",
 sass: "text/x-sass",
 scss: "text/x-scss",
 scala: "text/x-scala",
 scm: "text/x-scheme",
 sgml: "text/sgml",
 sgm: "text/sgml",
 tcl: "text/x-tcl",
 tex: "text/x-tex",
 txt: "text/plain",
 text: "text/plain",
 vb: "text/vbscript",
 vbscript: "text/vbscript",
 vhdl: "text/x-vhdl",
 vhd: "text/x-vhdl",
 wsdl: "text/xml",
 xsd: "text/xml",

 // Maths
 m: "text/x-matlab",
 mx: "application/mathematica",
 mxl: "application/vnd.recordare.musicxml",
 mxml: "application/mathml+xml",
 nb: "application/mathematica",
 nbp: "application/mathematica",
 nbw: "application/mathematica",
 nbt: "application/mathematica",
 nbz: "application/mathematica",
 nc: "application/x-netcdf",

 // Physics
 xtc: "chemical/x-xtc",
 xti: "chemical/x-xti",
 xyz: "chemical/x-xyz",
 pdb: "chemical/x-pdb",
 cml: "chemical/x-cml",
 mol: "chemical/x-mdl-molfile",
 sdf: "chemical/x-mdl-sdfile",
 sd: "chemical/x-mdl-sdfile",
 tmol: "chemical/x-mdl-tmolfile",
 mol2: "chemical/x-mol2",

 // Other
 bib: "text/x-bibtex",
 bbl: "text/x-bibtex",
 bibtex: "text/x-bibtex",

 // Fonts
 ttf: "font/ttf",
 otf: "font/otf",
 woff: "font/woff",
 woff2: "font/woff2",
 eot: "font/eot",
 sfnt: "font/sfnt",
 svgz: "font/svg",
 ttc: "font/ttc",
 otc: "font/otc",
 pfa: "font/pfa",
 pfb: "font/pfb",
 pfm: "font/pfm",
 pcf: "font/pcf",
 "pcf.z": "font/pcf.z",
 "pcf.gz": "font/pcf.gz",
 "pcf.bz2": "font/pcf.bz2",
 "pcf.xz": "font/pcf.xz",
 "pcf.lzma": "font/pcf.lzma",
 "pcf.tlz": "font/pcf.tlz",
 "pcf.txz": "font/pcf.txz",
 "pcf.tbz": "font/pcf.tbz",
 "pcf.tbz2": "font/pcf.tbz2",
 "pcf.tz": "font/pcf.tz",
 "pcf.taz": "font/pcf.taz",

 // Text
 md: "text/markdown",
 markdown: "text/markdown",
 nquads: "text/n3",
 rdfs: "text/rdfs+xml",

 // Markup languages

 htm: "text/html",
 html: "text/html",
 shtml: "text/html",
 xhtml: "application/xhtml+xml",
 xht: "application/xhtml+xml",
 xhtm: "application/xhtml+xml",
 xhtmls: "application/xhtml+xml",

 // OpenDocument
 odt: "application/vnd.oasis.opendocument.text",
 ott: "application/vnd.oasis.opendocument.text-template",
 ots: "application/vnd.oasis.opendocument.spreadsheet",
 otp: "application/vnd.oasis.opendocument.presentation",
 otg: "application/vnd.oasis.opendocument.graphics",
 oth: "application/vnd.oasis.opendocument.text-web",
 odi: "application/vnd.oasis.opendocument.image",
 odp: "application/vnd.oasis.opendocument.presentation",
 ods: "application/vnd.oasis.opendocument.spreadsheet",
 odg: "application/vnd.oasis.opendocument.graphics",
 odf: "application/vnd.oasis.opendocument.formula",
 odb: "application/vnd.oasis.opendocument.database",

 // Microsoft Office
 doc: "application/msword",
 dot: "application/msword",
 docx:
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
 dotx:
  "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
 docm: "application/vnd.ms-word.document.macroEnabled.12",
 dotm: "application/vnd.ms-word.template.macroEnabled.12",
 xls: "application/vnd.ms-excel",
 xlt: "application/vnd.ms-excel",
 xlm: "application/vnd.ms-excel",
 xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
 xltx: "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
 xlsm: "application/vnd.ms-excel.sheet.macroEnabled.12",
 xltm: "application/vnd.ms-excel.template.macroEnabled.12",
 xlam: "application/vnd.ms-excel.addin.macroEnabled.12",
 xlsb: "application/vnd.ms-excel.sheet.binary.macroEnabled.12",
 xla: "application/vnd.ms-excel",
 xll: "application/vnd.ms-excel",
 xlw: "application/vnd.ms-excel",
 ppt: "application/vnd.ms-powerpoint",
 pot: "application/vnd.ms-powerpoint",
 pps: "application/vnd.ms-powerpoint",
 ppa: "application/vnd.ms-powerpoint",
 pptx:
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
 potx: "application/vnd.openxmlformats-officedocument.presentationml.template",
 ppsx: "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
 ppam: "application/vnd.ms-powerpoint.addin.macroEnabled.12",
 pptm: "application/vnd.ms-powerpoint.presentation.macroEnabled.12",
 potm: "application/vnd.ms-powerpoint.template.macroEnabled.12",
 ppsm: "application/vnd.ms-powerpoint.slideshow.macroEnabled.12",
 mpp: "application/vnd.ms-project",
 mpt: "application/vnd.ms-project",
 wps: "application/vnd.ms-works",
 wks: "application/vnd.ms-works",
 wcm: "application/vnd.ms-works",

 pdf: "application/pdf",

 // Databases
 sql: "application/sql",
 db: "application/sql",
 db3: "application/sql",
 dbf: "application/sql",
 dbt: "application/sql",
 dbd: "application/sql",
 dba: "application/sql",
 dbs: "application/sql",
 dqy: "application/sql",
 dqf: "application/sql",
} as const;

export const IMAGE_MIME_TYPE = [
  MIME_TYPES.png,
  MIME_TYPES.gif,
  MIME_TYPES.jpeg,
  MIME_TYPES.svg,
  MIME_TYPES.webp,
];

export const PDF_MIME_TYPE = [MIME_TYPES.pdf];
export const MS_WORD_MIME_TYPE = [MIME_TYPES.doc, MIME_TYPES.docx];
export const MS_EXCEL_MIME_TYPE = [MIME_TYPES.xls, MIME_TYPES.xlsx];
export const MS_POWERPOINT_MIME_TYPE = [MIME_TYPES.ppt, MIME_TYPES.pptx];
export const EXE_MIME_TYPE = [MIME_TYPES.exe];
