import { storiesOf } from '@storybook/react';
import { attachDemos } from './attach-demos';
import * as demos from './index';

// @mantine/core
attachDemos(storiesOf('Accordion', module), demos.AccordionDemos);
attachDemos(storiesOf('ActionIcon', module), demos.ActionIconDemos);
attachDemos(storiesOf('Affix', module), demos.AffixDemos);
attachDemos(storiesOf('Alert', module), demos.AlertDemos);
attachDemos(storiesOf('Anchor', module), demos.AnchorDemos);
attachDemos(storiesOf('AppShell', module), demos.AppShellDemos);
attachDemos(storiesOf('AspectRatio', module), demos.AspectRatioDemos);
attachDemos(storiesOf('Autocomplete', module), demos.AutocompleteDemos);
attachDemos(storiesOf('Avatar', module), demos.AvatarDemos);
attachDemos(storiesOf('Badge', module), demos.BadgeDemos);
attachDemos(storiesOf('Blockquote', module), demos.BlockquoteDemos);
attachDemos(storiesOf('Box', module), demos.BoxDemos);
attachDemos(storiesOf('Breadcrumbs', module), demos.BreadcrumbsDemos);
attachDemos(storiesOf('Burger', module), demos.BurgerDemos);
attachDemos(storiesOf('Button', module), demos.ButtonDemos);
attachDemos(storiesOf('Card', module), demos.CardDemos);
attachDemos(storiesOf('Center', module), demos.CenterDemos);
attachDemos(storiesOf('Checkbox', module), demos.CheckboxDemos);
attachDemos(storiesOf('Chips', module), demos.ChipsDemos);
attachDemos(storiesOf('Code', module), demos.CodeDemos);
attachDemos(storiesOf('Collapse', module), demos.CollapseDemos);
attachDemos(storiesOf('ColorInput', module), demos.ColorInputDemos);
attachDemos(storiesOf('ColorPicker', module), demos.ColorPickerDemos);
attachDemos(storiesOf('ColorSwatch', module), demos.ColorSwatchDemos);
attachDemos(storiesOf('Container', module), demos.ContainerDemos);
attachDemos(storiesOf('Dialog', module), demos.DialogDemos);
attachDemos(storiesOf('Divider', module), demos.DividerDemos);
attachDemos(storiesOf('Drawer', module), demos.DrawerDemos);
attachDemos(storiesOf('Grid', module), demos.GridDemos);
attachDemos(storiesOf('Group', module), demos.GroupDemos);
attachDemos(storiesOf('Highlight', module), demos.HighlightDemos);
attachDemos(storiesOf('Image', module), demos.ImageDemos);
attachDemos(storiesOf('Input', module), demos.InputDemos);
attachDemos(storiesOf('InputWrapper', module), demos.InputWrapperDemos);
attachDemos(storiesOf('JsonInput', module), demos.JsonInputDemos);
attachDemos(storiesOf('Kbd', module), demos.KbdDemos);
attachDemos(storiesOf('List', module), demos.ListDemos);
attachDemos(storiesOf('Loader', module), demos.LoaderDemos);
attachDemos(storiesOf('LoadingOverlay', module), demos.LoadingOverlayDemos);
attachDemos(storiesOf('Mark', module), demos.MarkDemos);
attachDemos(storiesOf('MediaQuery', module), demos.MediaQueryDemos);
attachDemos(storiesOf('Menu', module), demos.MenuDemos);
attachDemos(storiesOf('Modal', module), demos.ModalDemos);
attachDemos(storiesOf('MultiSelect', module), demos.MultiSelectDemos);
attachDemos(storiesOf('NativeSelect', module), demos.NativeSelectDemos);
attachDemos(storiesOf('Notification', module), demos.NotificationDemos);
attachDemos(storiesOf('NumberInput', module), demos.NumberInputDemos);
attachDemos(storiesOf('Overlay', module), demos.OverlayDemos);
attachDemos(storiesOf('Pagination', module), demos.PaginationDemos);
attachDemos(storiesOf('Paper', module), demos.PaperDemos);
attachDemos(storiesOf('PasswordInput', module), demos.PasswordInputDemos);
attachDemos(storiesOf('Popover', module), demos.PopoverDemos);
attachDemos(storiesOf('Popper', module), demos.PopperDemos);
attachDemos(storiesOf('Progress', module), demos.ProgressDemos);
attachDemos(storiesOf('RadioGroup', module), demos.RadioGroupDemos);
attachDemos(storiesOf('RingProgress', module), demos.RingProgressDemos);
attachDemos(storiesOf('ScrollArea', module), demos.ScrollAreaDemos);
attachDemos(storiesOf('SegmentedControl', module), demos.SegmentedControlDemos);
attachDemos(storiesOf('Select', module), demos.SelectDemos);
attachDemos(storiesOf('SimpleGrid', module), demos.SimpleGridDemos);
attachDemos(storiesOf('Skeleton', module), demos.SkeletonDemos);
attachDemos(storiesOf('Slider', module), demos.SliderDemos);
attachDemos(storiesOf('Spoiler', module), demos.SpoilerDemos);
attachDemos(storiesOf('Stepper', module), demos.StepperDemos);
attachDemos(storiesOf('Switch', module), demos.SwitchDemos);
attachDemos(storiesOf('Table', module), demos.TableDemos);
attachDemos(storiesOf('Text', module), demos.TextDemos);
attachDemos(storiesOf('Textarea', module), demos.TextareaDemos);
attachDemos(storiesOf('TextInput', module), demos.TextInputDemos);
attachDemos(storiesOf('ThemeIcon', module), demos.ThemeIconDemos);
attachDemos(storiesOf('Timeline', module), demos.TimelineDemos);
attachDemos(storiesOf('Title', module), demos.TitleDemos);
attachDemos(storiesOf('Tooltip', module), demos.TooltipDemos);
attachDemos(storiesOf('TransferList', module), demos.TransferListDemos);
attachDemos(storiesOf('Transition', module), demos.TransitionDemos);
attachDemos(storiesOf('Stack', module), demos.StackDemos);
attachDemos(storiesOf('TypographyStylesProvider', module), demos.TypographyStylesProviderDemos);

// @mantine/dates
attachDemos(storiesOf('Calendar', module), demos.CalendarDemos);
attachDemos(storiesOf('DatePicker', module), demos.DatePickerDemos);
attachDemos(storiesOf('DateRangePicker', module), demos.DateRangePickerDemos);
attachDemos(storiesOf('Month', module), demos.MonthDemos);
attachDemos(storiesOf('RangeCalendar', module), demos.RangeCalendarDemos);
attachDemos(storiesOf('TimeInput', module), demos.TimeInputDemos);
attachDemos(storiesOf('TimeRangeInput', module), demos.TimeRangeInputDemos);

// Other packages
attachDemos(storiesOf('Dropzone', module), demos.DropzoneDemos);
attachDemos(storiesOf('Notifications System', module), demos.NotificationsDemos);
attachDemos(storiesOf('Prism', module), demos.PrismDemos);
attachDemos(storiesOf('RichTextEditor', module), demos.RichTextEditorDemos);
attachDemos(storiesOf('Styles', module), demos.CreateStylesDemos);
attachDemos(storiesOf('Theme', module), demos.ThemeDemos);
attachDemos(storiesOf('Spotlight', module), demos.SpotlightDemos);
attachDemos(storiesOf('Form', module), demos.FormDemos);

// @mantine/labs
attachDemos(storiesOf('PinInput', module), demos.PinInputDemos);
attachDemos(storiesOf('TagInput', module), demos.TagInputDemos);
