export const light = {
  colors: {
    'activityBar.activeBorder': '#fd8c73',
    'activityBar.background': '#ffffff',
    'activityBar.border': '#d0d7de',
    'activityBar.foreground': '#1f2328',
    'activityBar.inactiveForeground': '#656d76',
    'activityBarBadge.background': '#0969da',
    'activityBarBadge.foreground': '#ffffff',
    'badge.background': '#0969da',
    'badge.foreground': '#ffffff',
    'breadcrumb.activeSelectionForeground': '#656d76',
    'breadcrumb.focusForeground': '#1f2328',
    'breadcrumb.foreground': '#656d76',
    'breadcrumbPicker.background': '#ffffff',
    'button.background': '#1f883d',
    'button.foreground': '#ffffff',
    'button.hoverBackground': '#1a7f37',
    'button.secondaryBackground': '#ebecf0',
    'button.secondaryForeground': '#24292f',
    'button.secondaryHoverBackground': '#f3f4f6',
    'checkbox.background': '#f6f8fa',
    'checkbox.border': '#d0d7de',
    'debugConsole.errorForeground': '#cf222e',
    'debugConsole.infoForeground': '#57606a',
    'debugConsole.sourceForeground': '#9a6700',
    'debugConsole.warningForeground': '#7d4e00',
    'debugConsoleInputIcon.foreground': '#6639ba',
    'debugIcon.breakpointForeground': '#cf222e',
    'debugTokenExpression.boolean': '#116329',
    'debugTokenExpression.error': '#a40e26',
    'debugTokenExpression.name': '#0550ae',
    'debugTokenExpression.number': '#116329',
    'debugTokenExpression.string': '#0a3069',
    'debugTokenExpression.value': '#0a3069',
    'debugToolBar.background': '#ffffff',
    descriptionForeground: '#656d76',
    'diffEditor.insertedLineBackground': '#aceebb4d',
    'diffEditor.insertedTextBackground': '#6fdd8b80',
    'diffEditor.removedLineBackground': '#ffcecb4d',
    'diffEditor.removedTextBackground': '#ff818266',
    'dropdown.background': '#ffffff',
    'dropdown.border': '#d0d7de',
    'dropdown.foreground': '#1f2328',
    'dropdown.listBackground': '#ffffff',
    'editor.background': '#ffffff',
    'editor.findMatchBackground': '#bf8700',
    'editor.findMatchHighlightBackground': '#fae17d80',
    'editor.focusedStackFrameHighlightBackground': '#4ac26b66',
    'editor.foldBackground': '#6e77811a',
    'editor.foreground': '#1f2328',
    'editor.lineHighlightBackground': '#eaeef280',
    'editor.linkedEditingBackground': '#0969da12',
    'editor.selectionHighlightBackground': '#4ac26b40',
    'editor.stackFrameHighlightBackground': '#d4a72c66',
    'editor.wordHighlightBackground': '#eaeef280',
    'editor.wordHighlightBorder': '#afb8c199',
    'editor.wordHighlightStrongBackground': '#afb8c14d',
    'editor.wordHighlightStrongBorder': '#afb8c199',
    'editorBracketHighlight.foreground1': '#0969da',
    'editorBracketHighlight.foreground2': '#1a7f37',
    'editorBracketHighlight.foreground3': '#9a6700',
    'editorBracketHighlight.foreground4': '#cf222e',
    'editorBracketHighlight.foreground5': '#bf3989',
    'editorBracketHighlight.foreground6': '#8250df',
    'editorBracketHighlight.unexpectedBracket.foreground': '#656d76',
    'editorBracketMatch.background': '#4ac26b40',
    'editorBracketMatch.border': '#4ac26b99',
    'editorCursor.foreground': '#0969da',
    'editorGroup.border': '#d0d7de',
    'editorGroupHeader.tabsBackground': '#f6f8fa',
    'editorGroupHeader.tabsBorder': '#d0d7de',
    'editorGutter.addedBackground': '#4ac26b66',
    'editorGutter.deletedBackground': '#ff818266',
    'editorGutter.modifiedBackground': '#d4a72c66',
    'editorIndentGuide.activeBackground': '#1f23283d',
    'editorIndentGuide.background': '#1f23281f',
    'editorInlayHint.background': '#afb8c133',
    'editorInlayHint.foreground': '#656d76',
    'editorInlayHint.paramBackground': '#afb8c133',
    'editorInlayHint.paramForeground': '#656d76',
    'editorInlayHint.typeBackground': '#afb8c133',
    'editorInlayHint.typeForeground': '#656d76',
    'editorLineNumber.activeForeground': '#1f2328',
    'editorLineNumber.foreground': '#8c959f',
    'editorOverviewRuler.border': '#ffffff',
    'editorWhitespace.foreground': '#afb8c1',
    'editorWidget.background': '#ffffff',
    errorForeground: '#cf222e',
    focusBorder: '#0969da',
    foreground: '#1f2328',
    'gitDecoration.addedResourceForeground': '#1a7f37',
    'gitDecoration.conflictingResourceForeground': '#bc4c00',
    'gitDecoration.deletedResourceForeground': '#cf222e',
    'gitDecoration.ignoredResourceForeground': '#6e7781',
    'gitDecoration.modifiedResourceForeground': '#9a6700',
    'gitDecoration.submoduleResourceForeground': '#656d76',
    'gitDecoration.untrackedResourceForeground': '#1a7f37',
    'icon.foreground': '#656d76',
    'input.background': '#ffffff',
    'input.border': '#d0d7de',
    'input.foreground': '#1f2328',
    'input.placeholderForeground': '#6e7781',
    'keybindingLabel.foreground': '#1f2328',
    'list.activeSelectionBackground': '#afb8c133',
    'list.activeSelectionForeground': '#1f2328',
    'list.focusBackground': '#ddf4ff',
    'list.focusForeground': '#1f2328',
    'list.highlightForeground': '#0969da',
    'list.hoverBackground': '#eaeef280',
    'list.hoverForeground': '#1f2328',
    'list.inactiveFocusBackground': '#ddf4ff',
    'list.inactiveSelectionBackground': '#afb8c133',
    'list.inactiveSelectionForeground': '#1f2328',
    'minimapSlider.activeBackground': '#8c959f47',
    'minimapSlider.background': '#8c959f33',
    'minimapSlider.hoverBackground': '#8c959f3d',
    'notificationCenterHeader.background': '#f6f8fa',
    'notificationCenterHeader.foreground': '#656d76',
    'notifications.background': '#ffffff',
    'notifications.border': '#d0d7de',
    'notifications.foreground': '#1f2328',
    'notificationsErrorIcon.foreground': '#cf222e',
    'notificationsInfoIcon.foreground': '#0969da',
    'notificationsWarningIcon.foreground': '#9a6700',
    'panel.background': '#f6f8fa',
    'panel.border': '#d0d7de',
    'panelInput.border': '#d0d7de',
    'panelTitle.activeBorder': '#fd8c73',
    'panelTitle.activeForeground': '#1f2328',
    'panelTitle.inactiveForeground': '#656d76',
    'pickerGroup.border': '#d0d7de',
    'pickerGroup.foreground': '#656d76',
    'progressBar.background': '#0969da',
    'quickInput.background': '#ffffff',
    'quickInput.foreground': '#1f2328',
    'scrollbar.shadow': '#6e778133',
    'scrollbarSlider.activeBackground': '#8c959f47',
    'scrollbarSlider.background': '#8c959f33',
    'scrollbarSlider.hoverBackground': '#8c959f3d',
    'settings.headerForeground': '#1f2328',
    'settings.modifiedItemIndicator': '#d4a72c66',
    'sideBar.background': '#f6f8fa',
    'sideBar.border': '#d0d7de',
    'sideBar.foreground': '#1f2328',
    'sideBarSectionHeader.background': '#f6f8fa',
    'sideBarSectionHeader.border': '#d0d7de',
    'sideBarSectionHeader.foreground': '#1f2328',
    'sideBarTitle.foreground': '#1f2328',
    'statusBar.background': '#ffffff',
    'statusBar.border': '#d0d7de',
    'statusBar.debuggingBackground': '#cf222e',
    'statusBar.debuggingForeground': '#ffffff',
    'statusBar.focusBorder': '#0969da80',
    'statusBar.foreground': '#656d76',
    'statusBar.noFolderBackground': '#ffffff',
    'statusBarItem.activeBackground': '#1f23281f',
    'statusBarItem.focusBorder': '#0969da',
    'statusBarItem.hoverBackground': '#1f232814',
    'statusBarItem.prominentBackground': '#afb8c133',
    'statusBarItem.remoteBackground': '#eaeef2',
    'statusBarItem.remoteForeground': '#1f2328',
    'symbolIcon.arrayForeground': '#953800',
    'symbolIcon.booleanForeground': '#0550ae',
    'symbolIcon.classForeground': '#953800',
    'symbolIcon.colorForeground': '#0a3069',
    'symbolIcon.constantForeground': '#116329',
    'symbolIcon.constructorForeground': '#3e1f79',
    'symbolIcon.enumeratorForeground': '#953800',
    'symbolIcon.enumeratorMemberForeground': '#0550ae',
    'symbolIcon.eventForeground': '#57606a',
    'symbolIcon.fieldForeground': '#953800',
    'symbolIcon.fileForeground': '#7d4e00',
    'symbolIcon.folderForeground': '#7d4e00',
    'symbolIcon.functionForeground': '#6639ba',
    'symbolIcon.interfaceForeground': '#953800',
    'symbolIcon.keyForeground': '#0550ae',
    'symbolIcon.keywordForeground': '#a40e26',
    'symbolIcon.methodForeground': '#6639ba',
    'symbolIcon.moduleForeground': '#a40e26',
    'symbolIcon.namespaceForeground': '#a40e26',
    'symbolIcon.nullForeground': '#0550ae',
    'symbolIcon.numberForeground': '#116329',
    'symbolIcon.objectForeground': '#953800',
    'symbolIcon.operatorForeground': '#0a3069',
    'symbolIcon.packageForeground': '#953800',
    'symbolIcon.propertyForeground': '#953800',
    'symbolIcon.referenceForeground': '#0550ae',
    'symbolIcon.snippetForeground': '#0550ae',
    'symbolIcon.stringForeground': '#0a3069',
    'symbolIcon.structForeground': '#953800',
    'symbolIcon.textForeground': '#0a3069',
    'symbolIcon.typeParameterForeground': '#0a3069',
    'symbolIcon.unitForeground': '#0550ae',
    'symbolIcon.variableForeground': '#953800',
    'tab.activeBackground': '#ffffff',
    'tab.activeBorder': '#ffffff',
    'tab.activeBorderTop': '#fd8c73',
    'tab.activeForeground': '#1f2328',
    'tab.border': '#d0d7de',
    'tab.hoverBackground': '#ffffff',
    'tab.inactiveBackground': '#f6f8fa',
    'tab.inactiveForeground': '#656d76',
    'tab.unfocusedActiveBorder': '#ffffff',
    'tab.unfocusedActiveBorderTop': '#d0d7de',
    'tab.unfocusedHoverBackground': '#eaeef280',
    'terminal.ansiBlack': '#24292f',
    'terminal.ansiBlue': '#0969da',
    'terminal.ansiBrightBlack': '#57606a',
    'terminal.ansiBrightBlue': '#218bff',
    'terminal.ansiBrightCyan': '#3192aa',
    'terminal.ansiBrightGreen': '#1a7f37',
    'terminal.ansiBrightMagenta': '#a475f9',
    'terminal.ansiBrightRed': '#a40e26',
    'terminal.ansiBrightWhite': '#8c959f',
    'terminal.ansiBrightYellow': '#633c01',
    'terminal.ansiCyan': '#1b7c83',
    'terminal.ansiGreen': '#116329',
    'terminal.ansiMagenta': '#8250df',
    'terminal.ansiRed': '#cf222e',
    'terminal.ansiWhite': '#6e7781',
    'terminal.ansiYellow': '#4d2d00',
    'terminal.foreground': '#1f2328',
    'textBlockQuote.background': '#f6f8fa',
    'textBlockQuote.border': '#d0d7de',
    'textCodeBlock.background': '#afb8c133',
    'textLink.activeForeground': '#0969da',
    'textLink.foreground': '#0969da',
    'textPreformat.foreground': '#656d76',
    'textSeparator.foreground': '#d8dee4',
    'titleBar.activeBackground': '#ffffff',
    'titleBar.activeForeground': '#656d76',
    'titleBar.border': '#d0d7de',
    'titleBar.inactiveBackground': '#f6f8fa',
    'titleBar.inactiveForeground': '#656d76',
    'tree.indentGuidesStroke': '#d8dee4',
    'welcomePage.buttonBackground': '#f6f8fa',
    'welcomePage.buttonHoverBackground': '#f3f4f6',
  },
  displayName: 'GitHub Light Default',
  semanticHighlighting: true,
  tokenColors: [
    {
      scope: ['comment', 'punctuation.definition.comment', 'string.comment'],
      settings: {
        foreground: '#6e7781',
      },
    },
    {
      scope: ['constant.other.placeholder', 'constant.character'],
      settings: {
        foreground: '#cf222e',
      },
    },
    {
      scope: [
        'constant',
        'entity.name.constant',
        'variable.other.constant',
        'variable.other.enummember',
        'variable.language',
        'entity',
      ],
      settings: {
        foreground: '#0550ae',
      },
    },
    {
      scope: ['entity.name', 'meta.export.default', 'meta.definition.variable'],
      settings: {
        foreground: '#953800',
      },
    },
    {
      scope: [
        'variable.parameter.function',
        'meta.jsx.children',
        'meta.block',
        'meta.tag.attributes',
        'entity.name.constant',
        'meta.object.member',
        'meta.embedded.expression',
      ],
      settings: {
        foreground: '#1f2328',
      },
    },
    {
      scope: 'entity.name.function',
      settings: {
        foreground: '#8250df',
      },
    },
    {
      scope: ['entity.name.tag', 'support.class.component'],
      settings: {
        foreground: '#116329',
      },
    },
    {
      scope: 'keyword',
      settings: {
        foreground: '#cf222e',
      },
    },
    {
      scope: ['storage', 'storage.type'],
      settings: {
        foreground: '#cf222e',
      },
    },
    {
      scope: ['storage.modifier.package', 'storage.modifier.import', 'storage.type.java'],
      settings: {
        foreground: '#1f2328',
      },
    },
    {
      scope: ['string', 'string punctuation.section.embedded source'],
      settings: {
        foreground: '#0a3069',
      },
    },
    {
      scope: 'support',
      settings: {
        foreground: '#0550ae',
      },
    },
    {
      scope: 'meta.property-name',
      settings: {
        foreground: '#0550ae',
      },
    },
    {
      scope: 'variable',
      settings: {
        foreground: '#953800',
      },
    },
    {
      scope: 'variable.other',
      settings: {
        foreground: '#1f2328',
      },
    },
    {
      scope: 'invalid.broken',
      settings: {
        fontStyle: 'italic',
        foreground: '#82071e',
      },
    },
    {
      scope: 'invalid.deprecated',
      settings: {
        fontStyle: 'italic',
        foreground: '#82071e',
      },
    },
    {
      scope: 'invalid.illegal',
      settings: {
        fontStyle: 'italic',
        foreground: '#82071e',
      },
    },
    {
      scope: 'invalid.unimplemented',
      settings: {
        fontStyle: 'italic',
        foreground: '#82071e',
      },
    },
    {
      scope: 'carriage-return',
      settings: {
        background: '#cf222e',
        content: '^M',
        fontStyle: 'italic underline',
        foreground: '#f6f8fa',
      },
    },
    {
      scope: 'message.error',
      settings: {
        foreground: '#82071e',
      },
    },
    {
      scope: 'string variable',
      settings: {
        foreground: '#0550ae',
      },
    },
    {
      scope: ['source.regexp', 'string.regexp'],
      settings: {
        foreground: '#0a3069',
      },
    },
    {
      scope: [
        'string.regexp.character-class',
        'string.regexp constant.character.escape',
        'string.regexp source.ruby.embedded',
        'string.regexp string.regexp.arbitrary-repitition',
      ],
      settings: {
        foreground: '#0a3069',
      },
    },
    {
      scope: 'string.regexp constant.character.escape',
      settings: {
        fontStyle: 'bold',
        foreground: '#116329',
      },
    },
    {
      scope: 'support.constant',
      settings: {
        foreground: '#0550ae',
      },
    },
    {
      scope: 'support.variable',
      settings: {
        foreground: '#0550ae',
      },
    },
    {
      scope: 'support.type.property-name.json',
      settings: {
        foreground: '#116329',
      },
    },
    {
      scope: 'meta.module-reference',
      settings: {
        foreground: '#0550ae',
      },
    },
    {
      scope: 'punctuation.definition.list.begin.markdown',
      settings: {
        foreground: '#953800',
      },
    },
    {
      scope: ['markup.heading', 'markup.heading entity.name'],
      settings: {
        fontStyle: 'bold',
        foreground: '#0550ae',
      },
    },
    {
      scope: 'markup.quote',
      settings: {
        foreground: '#116329',
      },
    },
    {
      scope: 'markup.italic',
      settings: {
        fontStyle: 'italic',
        foreground: '#1f2328',
      },
    },
    {
      scope: 'markup.bold',
      settings: {
        fontStyle: 'bold',
        foreground: '#1f2328',
      },
    },
    {
      scope: ['markup.underline'],
      settings: {
        fontStyle: 'underline',
      },
    },
    {
      scope: ['markup.strikethrough'],
      settings: {
        fontStyle: 'strikethrough',
      },
    },
    {
      scope: 'markup.inline.raw',
      settings: {
        foreground: '#0550ae',
      },
    },
    {
      scope: ['markup.deleted', 'meta.diff.header.from-file', 'punctuation.definition.deleted'],
      settings: {
        background: '#ffebe9',
        foreground: '#82071e',
      },
    },
    {
      scope: ['punctuation.section.embedded'],
      settings: {
        foreground: '#cf222e',
      },
    },
    {
      scope: ['markup.inserted', 'meta.diff.header.to-file', 'punctuation.definition.inserted'],
      settings: {
        background: '#dafbe1',
        foreground: '#116329',
      },
    },
    {
      scope: ['markup.changed', 'punctuation.definition.changed'],
      settings: {
        background: '#ffd8b5',
        foreground: '#953800',
      },
    },
    {
      scope: ['markup.ignored', 'markup.untracked'],
      settings: {
        background: '#0550ae',
        foreground: '#eaeef2',
      },
    },
    {
      scope: 'meta.diff.range',
      settings: {
        fontStyle: 'bold',
        foreground: '#8250df',
      },
    },
    {
      scope: 'meta.diff.header',
      settings: {
        foreground: '#0550ae',
      },
    },
    {
      scope: 'meta.separator',
      settings: {
        fontStyle: 'bold',
        foreground: '#0550ae',
      },
    },
    {
      scope: 'meta.output',
      settings: {
        foreground: '#0550ae',
      },
    },
    {
      scope: [
        'brackethighlighter.tag',
        'brackethighlighter.curly',
        'brackethighlighter.round',
        'brackethighlighter.square',
        'brackethighlighter.angle',
        'brackethighlighter.quote',
      ],
      settings: {
        foreground: '#57606a',
      },
    },
    {
      scope: 'brackethighlighter.unmatched',
      settings: {
        foreground: '#82071e',
      },
    },
    {
      scope: ['constant.other.reference.link', 'string.other.link'],
      settings: {
        foreground: '#0a3069',
      },
    },
  ],
  type: 'light',
};

export const dark = {
  colors: {
    'activityBar.activeBorder': '#f78166',
    'activityBar.background': '#0d1117',
    'activityBar.border': '#30363d',
    'activityBar.foreground': '#e6edf3',
    'activityBar.inactiveForeground': '#7d8590',
    'activityBarBadge.background': '#1f6feb',
    'activityBarBadge.foreground': '#ffffff',
    'badge.background': '#1f6feb',
    'badge.foreground': '#ffffff',
    'breadcrumb.activeSelectionForeground': '#7d8590',
    'breadcrumb.focusForeground': '#e6edf3',
    'breadcrumb.foreground': '#7d8590',
    'breadcrumbPicker.background': '#161b22',
    'button.background': '#238636',
    'button.foreground': '#ffffff',
    'button.hoverBackground': '#2ea043',
    'button.secondaryBackground': '#282e33',
    'button.secondaryForeground': '#c9d1d9',
    'button.secondaryHoverBackground': '#30363d',
    'checkbox.background': '#161b22',
    'checkbox.border': '#30363d',
    'debugConsole.errorForeground': '#ffa198',
    'debugConsole.infoForeground': '#8b949e',
    'debugConsole.sourceForeground': '#e3b341',
    'debugConsole.warningForeground': '#d29922',
    'debugConsoleInputIcon.foreground': '#bc8cff',
    'debugIcon.breakpointForeground': '#f85149',
    'debugTokenExpression.boolean': '#56d364',
    'debugTokenExpression.error': '#ffa198',
    'debugTokenExpression.name': '#79c0ff',
    'debugTokenExpression.number': '#56d364',
    'debugTokenExpression.string': '#a5d6ff',
    'debugTokenExpression.value': '#a5d6ff',
    'debugToolBar.background': '#161b22',
    descriptionForeground: '#7d8590',
    'diffEditor.insertedLineBackground': '#23863626',
    'diffEditor.insertedTextBackground': '#3fb9504d',
    'diffEditor.removedLineBackground': '#da363326',
    'diffEditor.removedTextBackground': '#ff7b724d',
    'dropdown.background': '#161b22',
    'dropdown.border': '#30363d',
    'dropdown.foreground': '#e6edf3',
    'dropdown.listBackground': '#161b22',
    'editor.background': '#0d1117',
    'editor.findMatchBackground': '#9e6a03',
    'editor.findMatchHighlightBackground': '#f2cc6080',
    'editor.focusedStackFrameHighlightBackground': '#2ea04366',
    'editor.foldBackground': '#6e76811a',
    'editor.foreground': '#e6edf3',
    'editor.lineHighlightBackground': '#6e76811a',
    'editor.linkedEditingBackground': '#2f81f712',
    'editor.selectionHighlightBackground': '#3fb95040',
    'editor.stackFrameHighlightBackground': '#bb800966',
    'editor.wordHighlightBackground': '#6e768180',
    'editor.wordHighlightBorder': '#6e768199',
    'editor.wordHighlightStrongBackground': '#6e76814d',
    'editor.wordHighlightStrongBorder': '#6e768199',
    'editorBracketHighlight.foreground1': '#79c0ff',
    'editorBracketHighlight.foreground2': '#56d364',
    'editorBracketHighlight.foreground3': '#e3b341',
    'editorBracketHighlight.foreground4': '#ffa198',
    'editorBracketHighlight.foreground5': '#ff9bce',
    'editorBracketHighlight.foreground6': '#d2a8ff',
    'editorBracketHighlight.unexpectedBracket.foreground': '#7d8590',
    'editorBracketMatch.background': '#3fb95040',
    'editorBracketMatch.border': '#3fb95099',
    'editorCursor.foreground': '#2f81f7',
    'editorGroup.border': '#30363d',
    'editorGroupHeader.tabsBackground': '#010409',
    'editorGroupHeader.tabsBorder': '#30363d',
    'editorGutter.addedBackground': '#2ea04366',
    'editorGutter.deletedBackground': '#f8514966',
    'editorGutter.modifiedBackground': '#bb800966',
    'editorIndentGuide.activeBackground': '#e6edf33d',
    'editorIndentGuide.background': '#e6edf31f',
    'editorInlayHint.background': '#8b949e33',
    'editorInlayHint.foreground': '#7d8590',
    'editorInlayHint.paramBackground': '#8b949e33',
    'editorInlayHint.paramForeground': '#7d8590',
    'editorInlayHint.typeBackground': '#8b949e33',
    'editorInlayHint.typeForeground': '#7d8590',
    'editorLineNumber.activeForeground': '#e6edf3',
    'editorLineNumber.foreground': '#6e7681',
    'editorOverviewRuler.border': '#010409',
    'editorWhitespace.foreground': '#484f58',
    'editorWidget.background': '#161b22',
    errorForeground: '#f85149',
    focusBorder: '#1f6feb',
    foreground: '#e6edf3',
    'gitDecoration.addedResourceForeground': '#3fb950',
    'gitDecoration.conflictingResourceForeground': '#db6d28',
    'gitDecoration.deletedResourceForeground': '#f85149',
    'gitDecoration.ignoredResourceForeground': '#6e7681',
    'gitDecoration.modifiedResourceForeground': '#d29922',
    'gitDecoration.submoduleResourceForeground': '#7d8590',
    'gitDecoration.untrackedResourceForeground': '#3fb950',
    'icon.foreground': '#7d8590',
    'input.background': '#0d1117',
    'input.border': '#30363d',
    'input.foreground': '#e6edf3',
    'input.placeholderForeground': '#6e7681',
    'keybindingLabel.foreground': '#e6edf3',
    'list.activeSelectionBackground': '#6e768166',
    'list.activeSelectionForeground': '#e6edf3',
    'list.focusBackground': '#388bfd26',
    'list.focusForeground': '#e6edf3',
    'list.highlightForeground': '#2f81f7',
    'list.hoverBackground': '#6e76811a',
    'list.hoverForeground': '#e6edf3',
    'list.inactiveFocusBackground': '#388bfd26',
    'list.inactiveSelectionBackground': '#6e768166',
    'list.inactiveSelectionForeground': '#e6edf3',
    'minimapSlider.activeBackground': '#8b949e47',
    'minimapSlider.background': '#8b949e33',
    'minimapSlider.hoverBackground': '#8b949e3d',
    'notificationCenterHeader.background': '#161b22',
    'notificationCenterHeader.foreground': '#7d8590',
    'notifications.background': '#161b22',
    'notifications.border': '#30363d',
    'notifications.foreground': '#e6edf3',
    'notificationsErrorIcon.foreground': '#f85149',
    'notificationsInfoIcon.foreground': '#2f81f7',
    'notificationsWarningIcon.foreground': '#d29922',
    'panel.background': '#010409',
    'panel.border': '#30363d',
    'panelInput.border': '#30363d',
    'panelTitle.activeBorder': '#f78166',
    'panelTitle.activeForeground': '#e6edf3',
    'panelTitle.inactiveForeground': '#7d8590',
    'peekViewEditor.background': '#6e76811a',
    'peekViewEditor.matchHighlightBackground': '#bb800966',
    'peekViewResult.background': '#0d1117',
    'peekViewResult.matchHighlightBackground': '#bb800966',
    'pickerGroup.border': '#30363d',
    'pickerGroup.foreground': '#7d8590',
    'progressBar.background': '#1f6feb',
    'quickInput.background': '#161b22',
    'quickInput.foreground': '#e6edf3',
    'scrollbar.shadow': '#484f5833',
    'scrollbarSlider.activeBackground': '#8b949e47',
    'scrollbarSlider.background': '#8b949e33',
    'scrollbarSlider.hoverBackground': '#8b949e3d',
    'settings.headerForeground': '#e6edf3',
    'settings.modifiedItemIndicator': '#bb800966',
    'sideBar.background': '#010409',
    'sideBar.border': '#30363d',
    'sideBar.foreground': '#e6edf3',
    'sideBarSectionHeader.background': '#010409',
    'sideBarSectionHeader.border': '#30363d',
    'sideBarSectionHeader.foreground': '#e6edf3',
    'sideBarTitle.foreground': '#e6edf3',
    'statusBar.background': '#0d1117',
    'statusBar.border': '#30363d',
    'statusBar.debuggingBackground': '#da3633',
    'statusBar.debuggingForeground': '#ffffff',
    'statusBar.focusBorder': '#1f6feb80',
    'statusBar.foreground': '#7d8590',
    'statusBar.noFolderBackground': '#0d1117',
    'statusBarItem.activeBackground': '#e6edf31f',
    'statusBarItem.focusBorder': '#1f6feb',
    'statusBarItem.hoverBackground': '#e6edf314',
    'statusBarItem.prominentBackground': '#6e768166',
    'statusBarItem.remoteBackground': '#30363d',
    'statusBarItem.remoteForeground': '#e6edf3',
    'symbolIcon.arrayForeground': '#f0883e',
    'symbolIcon.booleanForeground': '#58a6ff',
    'symbolIcon.classForeground': '#f0883e',
    'symbolIcon.colorForeground': '#79c0ff',
    'symbolIcon.constantForeground': [
      '#aff5b4',
      '#7ee787',
      '#56d364',
      '#3fb950',
      '#2ea043',
      '#238636',
      '#196c2e',
      '#0f5323',
      '#033a16',
      '#04260f',
    ],
    'symbolIcon.constructorForeground': '#d2a8ff',
    'symbolIcon.enumeratorForeground': '#f0883e',
    'symbolIcon.enumeratorMemberForeground': '#58a6ff',
    'symbolIcon.eventForeground': '#6e7681',
    'symbolIcon.fieldForeground': '#f0883e',
    'symbolIcon.fileForeground': '#d29922',
    'symbolIcon.folderForeground': '#d29922',
    'symbolIcon.functionForeground': '#bc8cff',
    'symbolIcon.interfaceForeground': '#f0883e',
    'symbolIcon.keyForeground': '#58a6ff',
    'symbolIcon.keywordForeground': '#ff7b72',
    'symbolIcon.methodForeground': '#bc8cff',
    'symbolIcon.moduleForeground': '#ff7b72',
    'symbolIcon.namespaceForeground': '#ff7b72',
    'symbolIcon.nullForeground': '#58a6ff',
    'symbolIcon.numberForeground': '#3fb950',
    'symbolIcon.objectForeground': '#f0883e',
    'symbolIcon.operatorForeground': '#79c0ff',
    'symbolIcon.packageForeground': '#f0883e',
    'symbolIcon.propertyForeground': '#f0883e',
    'symbolIcon.referenceForeground': '#58a6ff',
    'symbolIcon.snippetForeground': '#58a6ff',
    'symbolIcon.stringForeground': '#79c0ff',
    'symbolIcon.structForeground': '#f0883e',
    'symbolIcon.textForeground': '#79c0ff',
    'symbolIcon.typeParameterForeground': '#79c0ff',
    'symbolIcon.unitForeground': '#58a6ff',
    'symbolIcon.variableForeground': '#f0883e',
    'tab.activeBackground': '#0d1117',
    'tab.activeBorder': '#0d1117',
    'tab.activeBorderTop': '#f78166',
    'tab.activeForeground': '#e6edf3',
    'tab.border': '#30363d',
    'tab.hoverBackground': '#0d1117',
    'tab.inactiveBackground': '#010409',
    'tab.inactiveForeground': '#7d8590',
    'tab.unfocusedActiveBorder': '#0d1117',
    'tab.unfocusedActiveBorderTop': '#30363d',
    'tab.unfocusedHoverBackground': '#6e76811a',
    'terminal.ansiBlack': '#484f58',
    'terminal.ansiBlue': '#58a6ff',
    'terminal.ansiBrightBlack': '#6e7681',
    'terminal.ansiBrightBlue': '#79c0ff',
    'terminal.ansiBrightCyan': '#56d4dd',
    'terminal.ansiBrightGreen': '#56d364',
    'terminal.ansiBrightMagenta': '#d2a8ff',
    'terminal.ansiBrightRed': '#ffa198',
    'terminal.ansiBrightWhite': '#ffffff',
    'terminal.ansiBrightYellow': '#e3b341',
    'terminal.ansiCyan': '#39c5cf',
    'terminal.ansiGreen': '#3fb950',
    'terminal.ansiMagenta': '#bc8cff',
    'terminal.ansiRed': '#ff7b72',
    'terminal.ansiWhite': '#b1bac4',
    'terminal.ansiYellow': '#d29922',
    'terminal.foreground': '#e6edf3',
    'textBlockQuote.background': '#010409',
    'textBlockQuote.border': '#30363d',
    'textCodeBlock.background': '#6e768166',
    'textLink.activeForeground': '#2f81f7',
    'textLink.foreground': '#2f81f7',
    'textPreformat.foreground': '#7d8590',
    'textSeparator.foreground': '#21262d',
    'titleBar.activeBackground': '#0d1117',
    'titleBar.activeForeground': '#7d8590',
    'titleBar.border': '#30363d',
    'titleBar.inactiveBackground': '#010409',
    'titleBar.inactiveForeground': '#7d8590',
    'tree.indentGuidesStroke': '#21262d',
    'welcomePage.buttonBackground': '#21262d',
    'welcomePage.buttonHoverBackground': '#30363d',
  },
  displayName: 'GitHub Dark Default',
  semanticHighlighting: true,
  tokenColors: [
    {
      scope: ['comment', 'punctuation.definition.comment', 'string.comment'],
      settings: {
        foreground: '#8b949e',
      },
    },
    {
      scope: ['constant.other.placeholder', 'constant.character'],
      settings: {
        foreground: '#ff7b72',
      },
    },
    {
      scope: [
        'constant',
        'entity.name.constant',
        'variable.other.constant',
        'variable.other.enummember',
        'variable.language',
        'entity',
      ],
      settings: {
        foreground: '#79c0ff',
      },
    },
    {
      scope: ['entity.name', 'meta.export.default', 'meta.definition.variable'],
      settings: {
        foreground: '#ffa657',
      },
    },
    {
      scope: [
        'variable.parameter.function',
        'meta.jsx.children',
        'meta.block',
        'meta.tag.attributes',
        'entity.name.constant',
        'meta.object.member',
        'meta.embedded.expression',
      ],
      settings: {
        foreground: '#e6edf3',
      },
    },
    {
      scope: 'entity.name.function',
      settings: {
        foreground: '#d2a8ff',
      },
    },
    {
      scope: ['entity.name.tag', 'support.class.component'],
      settings: {
        foreground: '#7ee787',
      },
    },
    {
      scope: 'keyword',
      settings: {
        foreground: '#ff7b72',
      },
    },
    {
      scope: ['storage', 'storage.type'],
      settings: {
        foreground: '#ff7b72',
      },
    },
    {
      scope: ['storage.modifier.package', 'storage.modifier.import', 'storage.type.java'],
      settings: {
        foreground: '#e6edf3',
      },
    },
    {
      scope: ['string', 'string punctuation.section.embedded source'],
      settings: {
        foreground: '#a5d6ff',
      },
    },
    {
      scope: 'support',
      settings: {
        foreground: '#79c0ff',
      },
    },
    {
      scope: 'meta.property-name',
      settings: {
        foreground: '#79c0ff',
      },
    },
    {
      scope: 'variable',
      settings: {
        foreground: '#ffa657',
      },
    },
    {
      scope: 'variable.other',
      settings: {
        foreground: '#e6edf3',
      },
    },
    {
      scope: 'invalid.broken',
      settings: {
        fontStyle: 'italic',
        foreground: '#ffa198',
      },
    },
    {
      scope: 'invalid.deprecated',
      settings: {
        fontStyle: 'italic',
        foreground: '#ffa198',
      },
    },
    {
      scope: 'invalid.illegal',
      settings: {
        fontStyle: 'italic',
        foreground: '#ffa198',
      },
    },
    {
      scope: 'invalid.unimplemented',
      settings: {
        fontStyle: 'italic',
        foreground: '#ffa198',
      },
    },
    {
      scope: 'carriage-return',
      settings: {
        background: '#ff7b72',
        content: '^M',
        fontStyle: 'italic underline',
        foreground: '#f0f6fc',
      },
    },
    {
      scope: 'message.error',
      settings: {
        foreground: '#ffa198',
      },
    },
    {
      scope: 'string variable',
      settings: {
        foreground: '#79c0ff',
      },
    },
    {
      scope: ['source.regexp', 'string.regexp'],
      settings: {
        foreground: '#a5d6ff',
      },
    },
    {
      scope: [
        'string.regexp.character-class',
        'string.regexp constant.character.escape',
        'string.regexp source.ruby.embedded',
        'string.regexp string.regexp.arbitrary-repitition',
      ],
      settings: {
        foreground: '#a5d6ff',
      },
    },
    {
      scope: 'string.regexp constant.character.escape',
      settings: {
        fontStyle: 'bold',
        foreground: '#7ee787',
      },
    },
    {
      scope: 'support.constant',
      settings: {
        foreground: '#79c0ff',
      },
    },
    {
      scope: 'support.variable',
      settings: {
        foreground: '#79c0ff',
      },
    },
    {
      scope: 'support.type.property-name.json',
      settings: {
        foreground: '#7ee787',
      },
    },
    {
      scope: 'meta.module-reference',
      settings: {
        foreground: '#79c0ff',
      },
    },
    {
      scope: 'punctuation.definition.list.begin.markdown',
      settings: {
        foreground: '#ffa657',
      },
    },
    {
      scope: ['markup.heading', 'markup.heading entity.name'],
      settings: {
        fontStyle: 'bold',
        foreground: '#79c0ff',
      },
    },
    {
      scope: 'markup.quote',
      settings: {
        foreground: '#7ee787',
      },
    },
    {
      scope: 'markup.italic',
      settings: {
        fontStyle: 'italic',
        foreground: '#e6edf3',
      },
    },
    {
      scope: 'markup.bold',
      settings: {
        fontStyle: 'bold',
        foreground: '#e6edf3',
      },
    },
    {
      scope: ['markup.underline'],
      settings: {
        fontStyle: 'underline',
      },
    },
    {
      scope: ['markup.strikethrough'],
      settings: {
        fontStyle: 'strikethrough',
      },
    },
    {
      scope: 'markup.inline.raw',
      settings: {
        foreground: '#79c0ff',
      },
    },
    {
      scope: ['markup.deleted', 'meta.diff.header.from-file', 'punctuation.definition.deleted'],
      settings: {
        background: '#490202',
        foreground: '#ffa198',
      },
    },
    {
      scope: ['punctuation.section.embedded'],
      settings: {
        foreground: '#ff7b72',
      },
    },
    {
      scope: ['markup.inserted', 'meta.diff.header.to-file', 'punctuation.definition.inserted'],
      settings: {
        background: '#04260f',
        foreground: '#7ee787',
      },
    },
    {
      scope: ['markup.changed', 'punctuation.definition.changed'],
      settings: {
        background: '#5a1e02',
        foreground: '#ffa657',
      },
    },
    {
      scope: ['markup.ignored', 'markup.untracked'],
      settings: {
        background: '#79c0ff',
        foreground: '#161b22',
      },
    },
    {
      scope: 'meta.diff.range',
      settings: {
        fontStyle: 'bold',
        foreground: '#d2a8ff',
      },
    },
    {
      scope: 'meta.diff.header',
      settings: {
        foreground: '#79c0ff',
      },
    },
    {
      scope: 'meta.separator',
      settings: {
        fontStyle: 'bold',
        foreground: '#79c0ff',
      },
    },
    {
      scope: 'meta.output',
      settings: {
        foreground: '#79c0ff',
      },
    },
    {
      scope: [
        'brackethighlighter.tag',
        'brackethighlighter.curly',
        'brackethighlighter.round',
        'brackethighlighter.square',
        'brackethighlighter.angle',
        'brackethighlighter.quote',
      ],
      settings: {
        foreground: '#8b949e',
      },
    },
    {
      scope: 'brackethighlighter.unmatched',
      settings: {
        foreground: '#ffa198',
      },
    },
    {
      scope: ['constant.other.reference.link', 'string.other.link'],
      settings: {
        foreground: '#a5d6ff',
      },
    },
  ],
  type: 'dark',
};
